# .github/workflows/ci-cd.yml
---
name: "Plublish to PyPI"

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: "True to print to STDOUT"
        required: true
        type: boolean

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/drf-misc
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Setup Python"
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Build distribution
        run: |
          python3 -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
